//! Proc-macro entrypoints.
//!
//! Exposes:
//! - Attribute macros: `#[sc("path")]`, `#[sc(module, "path")]`, and aliases.
//! - Function-like macros: `scoped_style!(...)`, `css!(...)`.
//!
//! The attribute macro defaults to strict primitive mode:
//! it registers scoped styles in runtime and returns user element unchanged.
//! A legacy inline style fallback mode is available via feature:
//! `legacy-inline-style-fallback`.

use proc_macro::TokenStream;
use quote::quote;
use syn::{
    Ident, ItemFn, LitStr, Token,
    parse::{Parse, ParseStream},
    parse_macro_input,
    punctuated::Punctuated,
};

mod compile;
mod expand;
mod scope;
use cssinjs::compiler::AcssCompiler;
use cssinjs::compiler::hash::{ScopeHashTarget, ScopeHasher, scope_hash_params_for};

enum ScopedArgs {
    Path(LitStr),
    Named {
        module: Ident,
        _comma: Token![,],
        path: LitStr,
    },
}

impl Parse for ScopedArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        if input.peek(LitStr) {
            Ok(Self::Path(input.parse()?))
        } else {
            Ok(Self::Named {
                module: input.parse()?,
                _comma: input.parse()?,
                path: input.parse()?,
            })
        }
    }
}

fn expand_scoped(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as ScopedArgs);
    let function = parse_macro_input!(item as ItemFn);
    let function = apply_scoped_transform(args, function);

    TokenStream::from(quote! { #function })
}

fn apply_scoped_transform(args: ScopedArgs, mut function: ItemFn) -> ItemFn {
    let init_tokens = match args {
        ScopedArgs::Path(path) => quote! {
            #[allow(unused_variables)]
            let css = ::cssinjs::scoped_style!(#path).scope();
        },
        ScopedArgs::Named { module, path, .. } => quote! {
            // Keep the named-module semantics (module is generated by the scoped_style macro).
            ::cssinjs::scoped_style!(#module, #path);
            #[allow(unused_variables)]
            let css = #module::get_scope().scope();
        },
    };

    let original_block = function.block;

    // NOTE: the closure wrapper is intentional:
    // it keeps `return` inside the user body working.
    if cfg!(feature = "legacy-inline-style-fallback") {
        function.block = Box::new(syn::parse_quote!({
            #init_tokens

            let __scoped_user_element: ::dioxus::prelude::Element = (|| #original_block)();
            let __scoped_css_text = ::cssinjs::inject_style(css);
            let __emit_scope_hash_attr = ::cssinjs::should_emit_scope_hash_attr();

            if __scoped_css_text.is_empty() {
                __scoped_user_element
            } else if __emit_scope_hash_attr {
                ::dioxus::prelude::rsx! {
                    ::dioxus::document::Style {
                        "data-css-hash": "{css}",
                        "{__scoped_css_text}"
                    }
                    {__scoped_user_element}
                }
            } else {
                ::dioxus::prelude::rsx! {
                    ::dioxus::document::Style {
                        "{__scoped_css_text}"
                    }
                    {__scoped_user_element}
                }
            }
        }));
    } else {
        function.block = Box::new(syn::parse_quote!({
            #init_tokens
            let __scoped_user_element: ::dioxus::prelude::Element = (|| #original_block)();
            let _ = css;
            __scoped_user_element
        }));
    }
    function
}

/// Injects `let css = scoped_style!(...).scope();` at function start.
///
/// Usage:
/// - `#[scoped("assets/layout.scss")]`
/// - `#[scoped(my_style, "assets/layout.scss")]`
#[proc_macro_attribute]
pub fn scoped(attr: TokenStream, item: TokenStream) -> TokenStream {
    expand_scoped(attr, item)
}

/// Ultra-short alias: `#[sc("assets/layout.scss")]` or `#[sc(my_style, "path")]`.
#[proc_macro_attribute]
pub fn sc(attr: TokenStream, item: TokenStream) -> TokenStream {
    expand_scoped(attr, item)
}

/// Backward-compatible alias for old call sites.
#[deprecated(note = "use #[scoped(...)] or #[sc(...)]")]
#[proc_macro_attribute]
pub fn scoped_asset_scope(attr: TokenStream, item: TokenStream) -> TokenStream {
    expand_scoped(attr, item)
}

/// Backward-compatible alias used by existing component modules.
#[deprecated(note = "use #[scoped(...)] or #[sc(...)]")]
#[proc_macro_attribute]
pub fn with_css(attr: TokenStream, item: TokenStream) -> TokenStream {
    expand_scoped(attr, item)
}

/// SCSS-explicit alias of `with_css`.
#[deprecated(note = "use #[scoped(...)] with .scss source")]
#[proc_macro_attribute]
pub fn with_scss(attr: TokenStream, item: TokenStream) -> TokenStream {
    expand_scoped(attr, item)
}

/// ACSS-explicit alias of `with_css`.
#[deprecated(note = "use #[scoped(...)] with .acss source")]
#[proc_macro_attribute]
pub fn with_acss(attr: TokenStream, item: TokenStream) -> TokenStream {
    expand_scoped(attr, item)
}

/// `scoped_style!(...)` function-like macro.
///
/// Supported forms:
/// - `scoped_style!("assets/a.scss")`
/// - `scoped_style!(my_style, "assets/a.scss")`
#[proc_macro]
pub fn scoped_style(input: TokenStream) -> TokenStream {
    expand::scoped_style_impl(input)
}

/// `css!("color:red; padding:8px;")` function-like macro.
#[proc_macro]
pub fn css(input: TokenStream) -> TokenStream {
    expand::css_impl(input)
}

/// Backward-compatible function-like alias.
///
/// Supports same forms as `scoped_style!(...)`.
#[deprecated(note = "use scoped_style!(...)")]
#[proc_macro]
pub fn component_with_css(input: TokenStream) -> TokenStream {
    expand::scoped_style_impl(input)
}

/// `acss!("property:value", "hover:color:red", ...)`
///
/// Compiles ACSS atoms at macro time, injects the stylesheet once,
/// and returns a `ScopedStyleSpec` that can be consumed by
/// `use_scoped_style(...)`.
#[proc_macro]
pub fn acss(input: TokenStream) -> TokenStream {
    let atoms = parse_macro_input!(input with Punctuated::<LitStr, Token![,]>::parse_terminated);
    let atoms = atoms.iter().map(LitStr::value).collect::<Vec<_>>();
    let source = atoms.join("\n");
    let minify = cfg!(not(debug_assertions));
    let compiled = match AcssCompiler::compile_with_meta(source.as_str(), minify) {
        Ok(v) => v,
        Err(e) => {
            return syn::Error::new(proc_macro2::Span::call_site(), e)
                .to_compile_error()
                .into();
        }
    };

    if compiled.css.trim().is_empty() || compiled.classes.is_empty() {
        return TokenStream::from(quote! {
            ::cssinjs::ScopedStyleSpec::new("", "", "", "", &[])
        });
    }
    let normalized_css =
        compile::StyleCompiler::normalize_css(compiled.css.as_str(), minify, "inline.acss");

    let scope_cfg = scope_hash_params_for(ScopeHashTarget::AcssMacro);
    let scope = ScopeHasher::generate_with_cfg(normalized_css.as_str(), None, scope_cfg.as_cfg());
    let css_lit = LitStr::new(normalized_css.as_str(), proc_macro2::Span::call_site());
    let class_lit = LitStr::new(
        compiled.classes.join(" ").as_str(),
        proc_macro2::Span::call_site(),
    );
    let class_entries = compiled
        .classes
        .iter()
        .map(|class_name| {
            quote! { ::cssinjs::ScopedClassEntry::new(#class_name, #class_name) }
        })
        .collect::<Vec<_>>();

    TokenStream::from(quote! {{
        use ::std::sync::OnceLock;
        static STYLE_INSTANCE: OnceLock<::cssinjs::ScopedStyle> = OnceLock::new();
        const STYLE_CLASSES: &[::cssinjs::ScopedClassEntry] = &[#(#class_entries),*];
        let _ = STYLE_INSTANCE.get_or_init(|| ::cssinjs::ScopedStyle::new(#scope, #css_lit));
        ::cssinjs::ScopedStyleSpec::new(
            #scope,
            #css_lit,
            #scope,
            #class_lit,
            STYLE_CLASSES,
        )
    }})
}
